swagger: "2.0"

info:
  title: Dataverse Metrics API
  description: An API for Dataverse metrics. (internal use)
  version: 0.5.0

# the domain of the service
host: 127.0.0.1:8000
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /metrics/v1
produces:
  - application/json
  
{% for endpoint in endpoints %}
{{ endpoint }}
{% endfor %}

# ------------------------------
# Define reusable parameters:
# ------------------------------
parameters:
  startDateParam:
    name: start_date
    in: query
    description: Optional. Inclusive start date in YYYY-MM-DD format
    type: string
  endDateParam:
    name: end_date
    in: query
    description: Optional. Inclusive end date in YYYY-MM-DD format
    type: string
  selectedYearParam:
    name: selected_year
    in: query
    description: Optional. Selected year in YYYY format
    type: string
  timeSortParam:
    name: time_sort
    in: query
    description: Optional. Sort by time.  'a' = ascending; 'd' = descending
    type: string
  prettyJSONParam:
    name: pretty
    in: query
    description: Optional. Returns HTML response showing formatted JSON
    type: boolean

# ------------------------------
# Define response definitions
# ------------------------------
definitions:
  MonthCount:
    properties:
      cnt:
        type: integer
      running_total:
        type: integer
      yyyy_mm:
        type: string
      month_name:
        type: string
      year_num:
        type: integer
      month_num:
        type: integer
  MonthCounts:
    type: array
    items:
      $ref: "#/definitions/MonthCount"
